# symbols.py

# --- NIFTY 50 (Core Bluechip - Super Liquid) ---
NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "BHARTIARTL", "SBIN", "LTIM",
    "HINDUNILVR", "ITC", "LT", "BAJFINANCE", "MARUTI", "HCLTECH", "SUNPHARMA", "AXISBANK",
    "ADANIENT", "ULTRACEMCO", "TITAN", "NTPC", "POWERGRID", "TATASTEEL", "ASIANPAINT",
    "COALINDIA", "M&M", "JIOFIN", "ADANIPORTS", "BAJAJ-AUTO", "BPCL", "CIPLA", "EICHERMOT",
    "GRASIM", "HEROMOTOCO", "INDUSINDBK", "JSWSTEEL", "KOTAKBANK", "NESTLEIND", "ONGC",
    "TATACONSUM", "TATAMOTORS", "TECHM", "WIPRO"
]

# --- NIFTY NEXT 50 (High Momentum Large-Cap) ---
NIFTY_NEXT_50 = [
    "ETERNAL", "HAL", "IRFC", "IOC", "RECLTD", "PFC", "DLF", "CHOLAFIN", "BEL", "PIDILITIND",
    "GODREJCP", "BANKBARODA", "PNB", "SIEMENS", "GAIL", "ABB", "TRENT", "AMBUJACEM", 
    "INDIGO", "TATAELXSI", "COLPAL", "VEDL", "MUTHOOTFIN", "SRF", "AUROPHARMA"
]

# --- NIFTY MIDCAP 150 (Selected High-Volume Quality Mid-Caps) ---
MIDCAP_150 = [
    "VOLTAS", "OBEROIRLTY", "POLYCAB", "MAXHEALTH", "PERSISTENT", "KPITTECH", "TATACOMM",
    "CONCOR", "CUMMINSIND", "ASHOKLEY", "BALKRISIND", "DIXON", "SUPREMEIND", "ASTRAL",
    "MRF", "DALBHARAT", "BHARATFORG", "LUPIN", "COFORGE", "MPHASIS", "PIIND", "NMDC",
    "SAIL", "GMRINFRA", "FEDERALBNK", "IDFCFIRSTB", "IDEA", "YESBANK", "RVNL"
]
