# symbols.py

# --- NIFTY 100 LARGE-CAP STOCKS ---
LARGE_CAP_STOCKS = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", 
    "BHARTIARTL", "SBIN", "LTIM", "HINDUNILVR", "ITC", 
    "LT", "BAJFINANCE", "MARUTI", "HCLTECH", "SUNPHARMA",
    "AXISBANK", "ADANIENT", "ULTRACEMCO", "TITAN", "NTPC", 
    "POWERGRID", "TATASTEEL", "ASIANPAINT", "COALINDIA", "M&M", 
    "JIOFIN", "INDIGO", "HAL", "ZOMATO", "ADANIPORTS"
]

# --- NIFTY MIDCAP 150 MID-CAP STOCKS ---
MID_CAP_STOCKS = [
    "VOLTAS", "BEL", "OBEROIRLTY", "POLYCAB", "MAXHEALTH", 
    "PFC", "RECLTD", "PERSISTENT", "KPITTECH", "TATACOMM", 
    "CONCOR", "CUMMINSIND", "ASHOKLEY", "BALKRISIND", "DIXON",
    "SUPREMEIND", "ASTRAL", "MRF", "DALBHARAT", "BHARATFORG", 
    "LUPIN", "AUROPHARMA", "COFORGE", "MPHASIS", "PIIND",
    "NMDC", "SAIL", "GMRINFRA", "FEDERALBNK", "IDFCFIRSTB"
]
